brew update
brew upgrade

brew install git
brew install docker
brew install boot2docker
brew install go
brew install heroku-toolbelt
brew install icdiff
brew install mariadb
brew install mongodb
brew install nginx
brew install nmap
brew install node
brew install rbenv
brew install rbenv-gem-rehash
brew install redis
brew install rsync
brew install ruby-build
brew install ssh-copy-id
brew install tree

brew cleanup
