cask_args appdir: '/Applications'

tap 'homebrew/dupes'
tap 'homebrew/services'

brew 'caskroom/cask/brew-cask'
brew 'git'
brew 'go'
brew 'heroku-toolbelt'
brew 'nginx'
brew 'nmap'
brew 'node'
brew 'rbenv'
brew 'rbenv-gem-rehash'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'tree'

# Quicklook plugins
cask 'betterzipql'
cask 'cert-quicklook'
cask 'kitematic'
cask 'provisionql'
cask 'qlcolorcode'
cask 'qlstephen'
cask 'qlmarkdown'
cask 'quicklook-json'
cask 'quicklook-csv'

# Apps
cask 'alfred'
cask 'atom'
cask 'dash'
cask 'dockertoolbox'
cask 'dropbox'
cask 'firefox'
cask 'get-lyrical'
cask 'gimp'
cask 'google-chrome'
cask 'handbrake'
cask 'istat-menus'
cask 'iterm2'
cask 'licecap'
cask 'logitech-gaming-software'
cask 'macdown'
cask 'mysqlworkbench'
cask 'openemu'
cask 'plex-media-server'
cask 'postgres'
cask 'private-internet-access'
cask 'robomongo'
cask 'sequel-pro'
cask 'skype'
cask 'slack'
cask 'sourcetree'
cask 'sonarr'
cask 'spectacle'
cask 'spotify'
cask 'teamviewer'
cask 'the-unarchiver'
cask 'utorrent'
cask 'virtualbox'
cask 'vagrant'
cask 'vlc'
